# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-EBNF
version:      1.03
version_from: lib/Parse/EBNF.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
